version: "3"
services:
  django: &django
    build:
      context: .
      dockerfile: ./Docker/Dockerfile
      args:
        - BUILD_ENVIRONMENT=development
    environment:
      - BUILD_ENVIRONMENT=development
    volumes:
      - .:/app:z
