version: "3"
networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet : ${NETWORK_SUBNET:-172.14.3.0/24}

services:
  django: &django
    container_name: Main-application
    image: local-app-image
    depends_on:
      - postgresql
      - redis
    networks:
      network:
        ipv4_address: ${MAIN_APP_IP:-172.14.3.5}
    env_file : 
      - ./.env

    ports:
      - '8080:8080'

    command : /start

  postgresql :
      image: postgres:latest
      container_name: postgres_data
      ports:
        - "5432:5432"
      env_file:
        - ./.env
      networks:
        network:
          ipv4_address: ${POSTGRES_DB_IP:-172.14.3.7}
          
      volumes:
        - postgres_data:/var/lib/postgresql/data
  redis:
    image: "redis:latest"
    env_file:
    - ./.env
    container_name: reids_container
    networks:
      network:
        ipv4_address: ${REDIS_IP:-172.14.3.9}

    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  nginx:
    image: nginx:stable-alpine
    networks:
      network:
        ipv4_address: ${NGINX_IP:-172.14.3.2}
    ports:
      - "80:80"
    environment:
      - NGINX_PROXY_PASS=${NGINX_PROXY_PASS:-http://${MAIN_APP_IP}:8080}
    volumes:
      - ./nginx.conf:/etc/nginx/default.conf:ro
volumes:
    postgres_data:
    redis_data: