version: "3"
networks:
  network:
    driver: bridge
services:
  django: &django
    container_name: Main-application
    image: local-app-image
    depends_on:
      - postgresql
      - redis
    networks:
      - network
    env_file : 
      - ./.env

    ports:
      - '8080:8080'

    command : /start

  postgresql :
      image: postgres:latest
      container_name: postgres_data
      ports:
        - "5432:5432"
      env_file:
        - ./.env
      networks:
        - network
      volumes:
        - postgres_data:/var/lib/postgresql/data
  redis:
    image: "redis:latest"
    env_file:
    - ./.env
    container_name: reids_container
    networks:
    - network
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data


volumes:
    postgres_data:
    redis_data: